%YAML 1.1
---
id: 55e84a6
title: API Change Causes Incompatibility
description: >
     The ROS rqt_plot tool was updated and its API changed, causing
     incompatibility problems in Kobuki's test suite.
classification: API Incompatibility (no CWE) #EVOLUTION
keywords: ['rqt', 'api', 'incompatibility', 'plot']
system: kobuki
severity: error
links: []
bug:
  phase: runtime-operation
  specificity: ROS-specific
  architectural-location: application-specific code
  application: test suite
  task: testing
  subsystem: test suite
  package: yujinrobot/kobuki_desktop/kobuki_qtestsuite
  languages:
    - Python
  detected-by: testing violation
  reported-by: member developer
  issue: https://github.com/yujinrobot/kobuki_desktop/issues/33
  time-reported: 2014-08-08T06:25:24Z
  reproducibility: always
  trace: |
    PluginManager._load_plugin() could not load plugin "kobuki_qtestsuite/Kobuki Test Suite":
    Traceback (most recent call last):
      File "/opt/ros/indigo/lib/python2.7/dist-packages/qt_gui/plugin_handler.py", line 98, in load
        self._load()
      File "/opt/ros/indigo/lib/python2.7/dist-packages/qt_gui/plugin_handler_direct.py", line 54, in _load
        self._plugin = self._plugin_provider.load(self._instance_id.plugin_id, self._context)
      File "/opt/ros/indigo/lib/python2.7/dist-packages/qt_gui/composite_plugin_provider.py", line 71, in load
        instance = plugin_provider.load(plugin_id, plugin_context)
      File "/opt/ros/indigo/lib/python2.7/dist-packages/qt_gui/composite_plugin_provider.py", line 71, in load
        instance = plugin_provider.load(plugin_id, plugin_context)
      File "/opt/ros/indigo/lib/python2.7/dist-packages/rqt_gui_py/ros_py_plugin_provider.py", line 60, in load
        return super(RosPyPluginProvider, self).load(plugin_id, plugin_context)
      File "/opt/ros/indigo/lib/python2.7/dist-packages/qt_gui/composite_plugin_provider.py", line 71, in load
        instance = plugin_provider.load(plugin_id, plugin_context)
      File "/opt/ros/indigo/lib/python2.7/dist-packages/rqt_gui/ros_plugin_provider.py", line 94, in load
        return class_ref(plugin_context)
      File "/home/jihoonl/research/ros/kobuki/src/kobuki_desktop/kobuki_qtestsuite/src/kobuki_qtestsuite/testsuite.py", line 43, in __init__
        self._widget.setupUi()
      File "/home/jihoonl/research/ros/kobuki/src/kobuki_desktop/kobuki_qtestsuite/src/kobuki_qtestsuite/testsuite_widget.py", line 43, in setupUi
        self._ui.battery_profile_frame.setupUi(self._ui.configuration_dock.cmd_vel_topic_name())
      File "/home/jihoonl/research/ros/kobuki/src/kobuki_desktop/kobuki_qtestsuite/src/kobuki_qtestsuite/battery_profile_frame.py", line 51, in setupUi
        self._plot_widget.switch_data_plot_widget(FullSizeDataPlot(self._plot_widget))
      File "/opt/ros/indigo/lib/python2.7/dist-packages/rqt_plot/plot_widget.py", line 150, in switch_data_plot_widget
        self.data_plot.autoscroll(self.autoscroll_checkbox.isChecked())
    AttributeError: 'FullSizeDataPlot' object has no attribute 'autoscroll'
fix:
  repo: https://github.com/yujinrobot/kobuki_desktop
  hash: 5ee65b061a4a919b2a32e80087f4cb3e51e924ed | 6df4bd7e92aea5cf3696b20861fca0ed413ece6e | 55e84a61e50d23be20f1d7abb4018a635370bff4
  pull-request: null
  license: ['BSD']
  fix-in: ['kobuki_qtestsuite/src/kobuki_qtestsuite/battery_profile_frame.py', 'kobuki_qtestsuite/src/kobuki_qtestsuite/full_size_data_plot.py', 'kobuki_qtestsuite/src/kobuki_qtestsuite/gyro_drift_frame.py', 'kobuki_qtestsuite/src/kobuki_qtestsuite/testsuite_widget.py']
  languages:
    - Python
  time: 2014-08-11 (06:02)
